### ISSUE TITLE
RpcException: Error connecting to subchannel.

### ISSUE THREAD

**Issue by winzig** [qdrant/qdrant-dotnet#47]
I am writing a dotnet core app that I run on an AWS linux EC2 instance. (I develop it locally on a Mac.)

I had it working, allowing me to add vectors to a local instance of Qdrant, and then later querying it. I just setup my Qdrant client using this:

```csharp
public static QdrantClient VectorClient = new QdrantClient("localhost");
```

But now I'm trying to get this running remotely on AWS linux. So first I setup a new Qdrant instance using Qdrant Cloud, hosted at AWS. I now setup my client like this:

```csharp
public static QdrantClient VectorClient = new QdrantClient(new Uri("https://my-unique-qdrant-identifier.us-east-1-0.aws.cloud.qdrant.io:6334")), apiKey: "my-api-key");
```

Now, my querying of the Qdrant database works fine, but when I try to use VectorClient to INSERT new points, I get this error:

```csharp
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException: Connection refused")
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
   --- End of inner exception stack trace ---
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.PickAsync(PickContext context, Boolean waitForReady, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   at Qdrant.Client.QdrantClient.UpsertAsync(String collectionName, IReadOnlyList`1 points, Boolean wait, Nullable`1 ordering, ShardKeySelector shardKeySelector, CancellationToken cancellationToken)
   at DN.MachineLearning.Embeddings.Save(Single[] vectors, String destination, Nullable`1 id, Nullable`1 guid, IDictionary`2 payload) in /home/ec2-user/code/DN/MachineLearning/Embeddings.cs:line 216
   at DN.Motor.MotorIndexer.FinishIndexing(String source, DateTimeOffset startTime) in /home/ec2-user/tools/Vectorizer.cs:line 122
```

I call it using:

```csharp
await VectorClient.UpsertAsync(destination, new List<PointStruct> { point })
```

Any ideas what I'm doing wrong?

**Comment by winzig** [comment]
Turned out to be a mere typo!

**Comment by rishimalhan** [comment]
What was the typo?

**Comment by winzig** [comment]
@rishimalhan Apologies, I can't remember the details. I think it may have been a typo in the address I was using, but I can't remember. 

I'm currently using Qdrant Cloud with AWS as the underlying provider. 

I setup a singleton of their .NET client like this:

```csharp
public static QdrantClient VectorClient = new QdrantClient(new Uri(Constants.ApiUrlQdrant), apiKey: Constants.ApiKeyQdrant);
```

In my case, Constants.ApiUrQdrant looks something like this:

`https://MY-UNIQUE-IDENTIFIER.us-east-1-0.aws.cloud.qdrant.io:6334`

And then I have a helper method in one of my internal libraries called `Save` that does this:

```csharp
public static async Task<UpdateResult> Save(float[] vectors, ulong? id = null, Guid? guid = null, IDictionary<string, Value> payload = null)
{
    if (id != null || guid != null)
    {
        var point = new PointStruct
        {
            Id = (PointId) id ?? guid,
            Vectors = vectors
        };

        if (payload != null)
        {
            point.Payload.Add(payload);
        }

        return await VectorClient.UpsertAsync("my-vector-index", new List<PointStruct> { point });
    }
    
    return null; // nothing was saved
}
```

And then to search the db I do things like:

```csharp
VectorClient.SearchAsync
(
    "my-vector-index", 
    myVector, // float[]
    filter: vectorFilter,
    limit: 30
);
```

The `vectorFilter` could be null if no filtering is needed, but in our case we use it to filter down to a subset of indexed docs. So if in our initial payload we stored "MyCustomProperty" as a list of longs, like this:

```csharp
List<long> myCustomValues = new List<long> { 12345, 67890 };
payload["MyCustomProperty"] = new Value { ListValue = new ListValue { Values = { myCustomValues.Select(v => new Value { IntegerValue = v }) } } };
```

Then when we do a search later, the vectorFilter might be created like this:

```csharp
var vectorFilter = Conditions.Match("MyCustomProperty", 12345);
```

And the returned documents would only include those that had `12345` stored as a value in that field. (Not sure if anything has changed or if I'm doing it wrong, but the code we're using above to set a list of longs in a payload seems overly complicated!)
