### ISSUE TITLE
Grpc.Core.RpcException Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1). (HttpProtocolError)

### ISSUE THREAD

**Issue by amirvenus** [qdrant/qdrant-dotnet#53]
Hi,

I am running dotnet8 on macOS and I have not been able to connect to my Qdrant running on a Docker container over network. 

I get this exception on any calls including the following:

```
var collectionExists = await _client.CollectionExistsAsync("my_collection");
        
        
        await _client.CreateCollectionAsync("my_collection",
            new VectorParams { Size = 100, Distance = Distance.Cosine });
```

This is the exception:

```

Grpc.Core.RpcException
Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1). (HttpProtocolError) HttpProtocolException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1). (HttpProtocolError)", DebugException="System.Net.Http.HttpRequestException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1). (HttpProtocolError)")
   at Grpc.Net.Client.Internal.GrpcCall`2.GetResponseHeadersCoreAsync()
   at Qdrant.Client.QdrantClient.CollectionExistsAsync(String collectionName, CancellationToken cancellationToken)
```

I am certainly sure this only happens in this library as I can access it via a python client.

**Comment by Anush008** [comment]
Hi. Can you share how you're instantiating `_client`?

**Comment by russcam** [comment]
@amirvenus Also, what version of

- Qdrant .NET client
- Qdrant docker image

are you using?

**Comment by Anush008** [comment]
Could you https://github.com/qdrant/qdrant-dotnet/issues/53#issuecomment-2068935817?

**Comment by Anush008** [comment]
Can you please try
```
var client = new QdrantClient("localhost");
```
?
